# cshell configuration
# This file is installed as /etc/cshell.conf

# Prompt (ANSI colors are supported)
CSHELL_PROMPT='\033[1;36mcshell*\033[0m> '

# Set to 1 to enable colored command output where supported.
CSHELL_COLOR=1
